# Generated by Django 4.1 on 2023-04-17 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('Premier League', 'Premier League'), ('Bundesliga', 'Bundesliga'), ('La Liga', 'La Liga'), ('Serie A', 'Serie A'), ('Ligue 1', 'Ligue 1'), ('J リーグs', 'Jリーグ')], max_length=50, verbose_name='リーグ')),
                ('logo', models.ImageField(upload_to='image/', verbose_name='エンブレム')),
                ('location', models.CharField(max_length=150, verbose_name='本拠地')),
                ('temaname', models.CharField(max_length=50, verbose_name='チームネーム')),
                ('content', models.TextField(max_length=300, verbose_name='チーム紹介')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('content', models.TextField(max_length=140)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.team', verbose_name='チーム')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
                ('content', models.TextField(max_length=80, verbose_name='投稿内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post', verbose_name='投稿')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
