# Generated by Django 4.1 on 2023-04-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=80, verbose_name='投稿内容'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='team',
            name='content',
            field=models.CharField(max_length=300, verbose_name='チーム紹介'),
        ),
    ]
