# Generated by Django 4.1 on 2023-04-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_comment_content_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='post.team', verbose_name='チーム'),
        ),
    ]
