# Generated by Django 4.1 on 2023-04-19 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_title_alter_comment_post_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.team', verbose_name='チーム'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='タイトルC', max_length=50, verbose_name='タイトル'),
        ),
    ]
