# Generated by Django 4.1 on 2023-04-19 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_team_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.team', verbose_name='チーム'),
        ),
    ]
