# Generated by Django 4.1 on 2023-04-09 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_favorite_team_user_favorite_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content',
            field=models.CharField(max_length=500, verbose_name='自己紹介'),
        ),
    ]
