# Generated by Django 4.1 on 2023-04-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_league',
            field=models.CharField(choices=[('Premier League', 'Premier League'), ('Bundesliga', 'Bundesliga'), ('La Liga', 'La Liga'), ('Serie A', 'Serie A'), ('Ligue 1', 'Ligue 1'), ('J リーグs', 'Jリーグ')], default='Jリーグ', max_length=50, verbose_name='好きなリーグ'),
        ),
    ]
